-- CPU
CREATE TABLE SYS_MGR.SYS_CPU
(
    DATE_TIME         DATETIME     NOT NULL,
    HOST_NAME         VARCHAR(255) NOT NULL,
    IDLE              FLOAT,
    LOAD_AVERAGE_ZERO VARCHAR(255),
    LOAD_AVERAGE_ONE  VARCHAR(255),
    LOAD_AVERAGE_TWO  VARCHAR(255),
    SYS               FLOAT,
    USR               FLOAT,
    WAIT              FLOAT,
    CONSTRAINT PK_SYS_CPU PRIMARY KEY (DATE_TIME, HOST_NAME)
);

-- DISK
CREATE TABLE SYS_MGR.SYS_DISK
(
    DATE_TIME        DATETIME     NOT NULL,
    HOST_NAME        VARCHAR(255) NOT NULL,
    DISK_NAME        VARCHAR(255) NOT NULL,
    QUEUE            FLOAT,
    READ_LIVE_BYTES  NUMERIC(19, 0),
    READ_S           NUMERIC(19, 0),
    SERVICE_TIME     NUMERIC(19, 0),
    WRITE_LIVE_BYTES NUMERIC(19, 0),
    WRITES           NUMERIC(19, 0),
    TOTAL_BYTES      NUMERIC(19, 0),
    FREE_BYTES       NUMERIC(19, 0),
    USED_BYTES       NUMERIC(19, 0),
    USED_PERCENT     FLOAT,
    CONSTRAINT PK_SYS_DISK PRIMARY KEY (DATE_TIME, HOST_NAME, DISK_NAME)
);

-- EXCEPTION
CREATE TABLE SYS_MGR.SYS_EXCEPTION
(
    ID              NUMERIC(10, 0) NOT NULL,
    DATE_TIME       DATETIME,
    CLASS_NAME      VARCHAR(255),
    EXCEPTION_CLASS VARCHAR(255),
    MESSAGE         VARCHAR(255),
    METHOD_NAME     VARCHAR(255),
    CONSTRAINT PK_SYS_EXCEPTION PRIMARY KEY (ID)
);


-- MEMORY
CREATE TABLE SYS_MGR.SYS_MEMORY
(
    DATE_TIME     DATETIME     NOT NULL,
    HOST_NAME     VARCHAR(255) NOT NULL,
    ACTUAL_FREE   NUMERIC(19, 0),
    ACTUAL_USED   NUMERIC(19, 0),
    FREE_PERCENT  FLOAT,
    RAM           NUMERIC(19, 0),
    SWAP_FREE     NUMERIC(19, 0),
    SWAP_PAGE_IN  NUMERIC(19, 0),
    SWAP_PAGE_OUT NUMERIC(19, 0),
    SWAP_TOTAL    NUMERIC(19, 0),
    SWAP_USED     NUMERIC(19, 0),
    TOTAL         NUMERIC(19, 0),
    USED_PERCENT  FLOAT,
    CONSTRAINT PK_SYS_MEMORY PRIMARY KEY (DATE_TIME, HOST_NAME)
);

-- NETWORK
CREATE TABLE SYS_MGR.SYS_NETWORK
(
    DATE_TIME       DATETIME     NOT NULL,
    HOST_NAME       VARCHAR(255) NOT NULL,
    BROADCAST       VARCHAR(255),
    MAC_ADDR        VARCHAR(255),
    METRIC          NUMERIC(10, 0),
    MTU             NUMERIC(19, 0),
    NETMASK         VARCHAR(255),
    NET_IP_ADDR     VARCHAR(255),
    NIC_NAME        VARCHAR(255) NOT NULL,
    RX_BYTES        NUMERIC(19, 0),
    RX_DROPPED      NUMERIC(19, 0),
    RX_ERRORS       NUMERIC(19, 0),
    RX_LIVE_BYTES   NUMERIC(19, 0),
    RX_PACKETS      NUMERIC(19, 0),
    SPEED           NUMERIC(19, 0),
    TX_BYTES        NUMERIC(19, 0),
    TX_DROPPED      NUMERIC(19, 0),
    TX_ERRORS       NUMERIC(19, 0),
    TX_LIVE_BYTES   NUMERIC(19, 0),
    TX_PACKETS      NUMERIC(19, 0),
    CONSTRAINT PK_SYS_NETWORK PRIMARY KEY (DATE_TIME, HOST_NAME, NIC_NAME)
);

-- PROCESS
CREATE TABLE SYS_MGR.SYS_PROCESS
(
    DATE_TIME       DATETIME       NOT NULL,
    HOST_NAME       VARCHAR(255)   NOT NULL,
    ARGS            VARCHAR(255),
    CPU_USAGE       FLOAT,
    DNAME           VARCHAR(255),
    MEMORY_USAGE    FLOAT,
    MEMORY_USAGE_MB NUMERIC(19, 0),
    PID             NUMERIC(19, 0) NOT NULL,
    PPID            NUMERIC(19, 0),
    PRIORITY        NUMERIC(10, 0),
    PROCESS_NAME    VARCHAR(255),
    STATE           CHAR(1),
    THREADS         NUMERIC(19, 0),
    CONSTRAINT PK_SYS_PROCESS PRIMARY KEY (DATE_TIME, HOST_NAME, PID)
);